export const HERO_DATA = {
    name: "Tapan Patel",
    roles: ["Frontend Developer", "Backend Developer", "AI/ML Explorer", "Full-Stack Engineer"],
    description: "Crafting digital experiences with cutting-edge technology, from responsive frontends to scalable backends and intelligent AI solutions.",
};

export const ABOUT_DATA = {
    title: "About Me",
    description1: "I am Tapan Patel, a 3rd year B.Tech student specializing in Information and Communication Technology at Pandit Deendayal Energy University. I am deeply interested in space technology, advanced web development, and AI-driven solutions. With a strong academic background and technical foundation in full-stack development, database systems, and programming languages such as C, Python, and Java, I am committed to delivering innovative and effective solutions. I am passionate about applying technology to solve real-world problems and continuously advancing my knowledge in emerging fields such as Artificial Intelligence, Machine Learning, and the VLSI domain.",
    description2: "My journey is driven by curiosity and a desire to make a positive impact through technology. I thrive in collaborative environments and enjoy tackling complex challenges, whether it's building scalable web applications, exploring the frontiers of AI, or contributing to research in space technology. I am always eager to learn, grow, and contribute to projects that push the boundaries of innovation.",
    stats: {
        experience: "1.5+ Years",
    },
};

export const SKILLS_DATA = [
    { name: "React", level: 72, color: "#61DAFB", category: "Frontend" },
    { name: "Node.js", level: 70, color: "#339933", category: "Backend" },
    { name: "PostgreSQL", level: 68, color: "#336791", category: "Database" },
    { name: "MySQL", level: 66, color: "#00758F", category: "Database" },
    { name: "Express.js", level: 69, color: "#000000", category: "Backend" },
    { name: "JavaScript", level: 75, color: "#F7DF1E", category: "Frontend" },
    { name: "MongoDB", level: 70, color: "#47A248", category: "Database" },
    { name: "Python", level: 73, color: "#3776AB", category: "AI/ML" },
    { name: "Java", level: 71, color: "#007396", category: "Programming Language" },
    { name: "Power BI", level: 65, color: "#F2C811", category: "Data" },
    { name: "DSA", level: 55, color: "#8B5CF6", category: "Competitive Programming" },
    { name: "AI & ML", level: 47, color: "#00BFAE", category: "AI/ML" },
    {
        name: "Soft Skills",
        color: "#22c55e",
        category: "",
        isSoftSkills: true,
        icon: "https://img.icons8.com/external-flaticons-lineal-color-flat-icons/96/external-soft-skills-job-search-flaticons-lineal-color-flat-icons.png",
        content: "Leadership, Punctuality, Time Management, Project Planning, Problem Solving, Team-Work"
    },
];

export const EXPERIENCE_DATA = [
    {
        id: 1,
        title: "Frontend Development Intern",
        company: "Prodigy Infotech (Remote)",
        location: "",
        period: "June – July 2024",
        description: "Developed responsive, interactive web applications with a focus on user experience and cross-device compatibility. Practiced modern development workflows including version control and code reviews.",
        technologies: ["HTML", "CSS", "JavaScript", "React", "Responsive Design"],
        achievements: [
            "Built 5 production-quality projects including a weather app, portfolio website, and stopwatch",
            "Improved mobile responsiveness across all projects",
            "Enhanced user interactivity through advanced JavaScript features",
        ],
    },
    {
        id: 2,
        title: "Student Satellite Program – Sensor Research",
        company: "Pandit Deendayal Energy University / ISRO Collaboration",
        location: "",
        period: "Dec 2024 – Present",
        description: "Conducting in-depth research on sensor technologies for satellite payload integration. Evaluating feasibility and specifications to support mission planning and design.",
        technologies: ["Research & Analysis", "Sensor Systems", "Technical Documentation"],
        achievements: [
            "Analyzed past satellite missions to identify optimal sensor configurations",
            "Contributed to feasibility studies for payload integration",
            "Supported interdisciplinary team efforts in satellite design planning",
        ],
    },
    {
        id: 3,
        title: "Content & Research | Technical Writing | Documentation",
        company: "GDG On Campus, IEEE SPS PDEU, ENCODE",
        location: "",
        period: "Oct 2024 – April 2025",
        description: "Held multiple non-technical roles in student organizations, focusing on content creation, research, technical writing, and documentation for events and initiatives.",
        technologies: ["Content Writing", "Research", "Documentation", "Team Collaboration"],
        achievements: [
            "Core-Committee, Content & Research, Google Developers Groups On Campus – PDEU",
            "Sub-Committee, Technical Content Writing, IEEE SPS PDEU SBC",
            "Sub-Committee, Content & Documentation, ENCODE – The Computer Science Club – PDEU",
        ],
    },
];

export const PROJECTS_DATA = [
    {
        id: 1,
        title: "Converse - Real-time Chat Application",
        description: "A full-stack real-time chat application with user authentication, group and private messaging, and a modern UI.",
        image: "/projects/converse.png",
        technologies: ["React", "Node.js", "Socket.io", "Express", "MongoDB"],
        category: "Full Stack",
        tags: ["Frontend", "Backend", "DBMS"],
        status: "Completed",
        github: "https://github.com/TAPAN-2835/Converse",
        live: "https://converse-uh0p.onrender.com/",
        problemStatement: "Bridging the gap in real-time communication by providing a seamless, feature-rich chat interface.",
        keyFeatures: ["Private/Group Messaging", "User Authentication", "Real-time Notifications", "Responsive Design"],
        details: "Converse is my first major full-stack project, designed to provide a seamless real-time chat experience. It features user authentication, group and private messaging, message notifications, and a responsive, modern interface. Deployed on Render, Converse demonstrates my ability to build, deploy, and maintain production-ready web applications.",
    },
    {
        id: 7,
        title: "CodePulse - Full-Stack Interview Platform",
        description: "An advanced interview platform with a VSCode-powered editor, 1-on-1 video rooms, and real-time collaboration tools.",
        image: "/projects/codepulse.png",
        technologies: ["React", "Node.js", "Clerk", "Stream", "MongoDB", "Inngest"],
        category: "Full Stack",
        tags: ["Frontend", "Backend", "DBMS"],
        status: "Completed",
        github: "https://github.com/TAPAN-2835/CodePulse",
        live: "https://code-pulse-nu.vercel.app",
        problemStatement: "Traditional technical interview platforms often lack integrated, high-performance coding environments combined with stable video communication.",
        keyFeatures: ["VSCode-Powered Editor", "1-on-1 Video Interview", "Real-time Chat", "Secure Code Execution", "Background Job Processing"],
        details: "CodePulse is a feature-rich technical interview platform. It integrates a high-performance code editor with real-time video and chat capabilities. Built with scalability in mind, it uses Inngest for background jobs and Stream for video communication, ensuring a professional and reliable experience.",
    },
    {
        id: 8,
        title: "MacBook Pro - 3D Showcase",
        description: "An immersive Apple-style 3D website showcasing products with scroll-animated models and responsive UI.",
        image: "/projects/macbook.png",
        technologies: ["React", "Three.js", "GSAP", "Tailwind CSS", "Zustand"],
        category: "Web App",
        tags: ["Frontend"],
        status: "Completed",
        github: "https://github.com/TAPAN-2835/MacBook_GSAP",
        live: "https://mac-book-gsap-ruby.vercel.app",
        problemStatement: "Static product pages fail to capture the premium feel and intricate details of modern hardware.",
        keyFeatures: ["3D Product Scenes", "Scroll-triggered Animations", "Realistic Lighting", "Adaptive Layouts"],
        details: "A high-performance 3D product showcase inspired by Apple's design philosophy. Utilizing Three.js for rendering and GSAP for complex scroll interactions, this project delivers a premium user experience.",
    },
    {
        id: 2,
        title: "QuickKart - E-commerce Platform",
        description: "A modern, full-stack e-commerce platform for seamless online shopping, featuring product search, cart, and secure checkout.",
        image: "/projects/quickkart.png",
        technologies: ["React", "Node.js", "Express", "MongoDB", "Redux"],
        category: "Full Stack",
        tags: ["Frontend", "Backend", "DBMS"],
        status: "Completed",
        github: "https://github.com/TAPAN-2835/QuickKart",
        live: "https://quick-kart-i57j.vercel.app/",
        problemStatement: "Simplifying the online shopping journey with a performant and intuitive e-commerce interface.",
        keyFeatures: ["Product Search/Filtering", "Shopping Cart", "Checkout System", "User Profiles"],
        details: "QuickKart is a robust e-commerce web application designed for a smooth and intuitive shopping experience. It supports user authentication, product browsing, advanced search, shopping cart, and secure checkout. QuickKart demonstrates my ability to build scalable, user-friendlyStores, and is deployed on Vercel.",
    },
    {
        id: 9,
        title: "RasRang - GSAP Landing Page",
        description: "A visually striking and responsive landing page featuring smooth high-performance GSAP animations.",
        image: "/projects/rasrang_main.png",
        technologies: ["React", "GSAP", "Tailwind CSS"],
        category: "Web App",
        tags: ["Frontend"],
        status: "Completed",
        github: "https://github.com/TAPAN-2835/RasRang",
        live: "https://ras-rang.vercel.app",
        problemStatement: "Modern websites need to stand out with micro-interactions and animations without sacrificing performance.",
        keyFeatures: ["Smooth Scroll Interactions", "Responsive Transitions", "Modern UI Aesthetic"],
        details: "RasRang is an exploration into the capabilities of GSAP for building interactive landing pages. It focuses on performance optimization and creating a unique brand experience through motion.",
    },
    {
        id: 10,
        title: "Dreamify - AI Image Generator",
        description: "A full-stack AI-powered image generation platform that transforms text descriptions into unique, high-quality visuals.",
        image: "/projects/dreamify.png",
        technologies: ["React", "Node.js", "Express", "MongoDB", "Stripe", "Tailwind CSS"],
        category: "Full Stack",
        tags: ["Frontend", "Backend", "AI"],
        status: "Completed",
        github: "https://github.com/TAPAN-2835/Dreamify",
        live: "https://dreamifyy.vercel.app",
        problemStatement: "Bridging the gap between imagination and visual creation through high-performance AI generation.",
        keyFeatures: ["Text-to-Image Generation", "Credit-based System", "Stripe & Razorpay Integration", "User Authentication", "Responsive Image Gallery"],
        details: "Dreamify is a comprehensive AI Image Generator platform built using the MERN stack. It allows users to generate high-quality images from text prompts and features a sleek UI with Framer Motion animations.",
    },
    {
        id: 3,
        title: "Artificial Intelligence: Agentic AI, Gen AI, and RL",
        description: "A comprehensive collection of study materials and implementations exploring Agentic AI, Generative AI, and Reinforcement Learning.",
        image: "https://placehold.co/400x300/7c3aed/ffffff?text=AI+GenAI+RL&font=roboto",
        technologies: ["Python", "Jupyter Notebook", "Reinforcement Learning", "Generative AI", "Agentic AI"],
        category: "AI",
        tags: ["AI/ML"],
        status: "Ongoing",
        github: "https://github.com/TAPAN-2835/Artificial-Intelligence-Agentic-AI-Gen-AI-and-RL",
        live: "",
        problemStatement: "Understanding and documenting the rapid evolution of complex AI architectures.",
        keyFeatures: ["Agentic Frameworks", "GenAI Implementation", "RL Algorithms", "Technical Documentation"],
        details: "This project is a deep dive into modern artificial intelligence, focusing on Agentic AI, Generative AI, and Reinforcement Learning. It features hands-on Jupyter Notebooks and Python scripts.",
    },
    {
        id: 6,
        title: "QRify - Instant QR Generator",
        description: "A lightweight web app for generating QR codes instantly with a focus on simplicity and performance.",
        image: "https://placehold.co/400x300/ca8a04/ffffff?text=QRify&font=roboto",
        technologies: ["JavaScript", "Node.js", "Express.js", "HTML", "CSS"],
        category: "Web App",
        tags: ["Backend"],
        status: "Completed",
        github: "https://github.com/TAPAN-2835/QRify",
        live: "",
        problemStatement: "Providing a quick tool for generating QR codes without intrusive ads.",
        keyFeatures: ["Instant Generation", "Downloadable QR Images", "Clean UI"],
        details: "QRify is a lightweight web application that allows users to generate QR codes on the fly. Built with Node.js, Express, and vanilla JavaScript.",
    },
    {
        id: 5,
        title: "EcoMiles - EcoTransitRewards Platform",
        description: "An innovative rewards-based platform to encourage sustainable commuting, featuring gamification and a user wallet.",
        image: "https://placehold.co/400x300/059669/ffffff?text=EcoMiles&font=roboto",
        technologies: ["Node.js", "Express.js", "SQLite", "EJS"],
        category: "Full Stack",
        tags: ["Frontend", "Backend", "DBMS"],
        status: "Ongoing",
        github: "https://github.com/TAPAN-2835/EcoMiles",
        live: "",
        problemStatement: "Reducing carbon footprints by incentivizing sustainable public transportation usage.",
        keyFeatures: ["Reward Points System", "Ticket Verification", "Leaderboards", "User Wallet"],
        details: "EcoMiles is a web application designed to promote eco-friendly commuting by rewarding users for sustainable travel choices. Built with Node.js, Express, and SQLite.",
    },
    {
        id: 4,
        title: "8-bit Subtractor (Synopsys Flow)",
        description: "ASIC digital backend design for an 8-bit subtractor using Synopsys EDA tools, from RTL to GDSII layout.",
        image: "https://placehold.co/400x300/334155/ffffff?text=8-bit+Subtractor&font=roboto",
        technologies: ["Verilog", "Tcl", "Synopsys VCS", "Design Compiler", "IC Compiler II"],
        category: "Academic",
        tags: ["Academic"],
        status: "Completed",
        github: "https://github.com/TAPAN-2835/TAPAN_23BIT158_8bit_Subtractor",
        live: "",
        problemStatement: "Navigating the complex industrial VLSI design flow to create hardware-ready digital circuits.",
        keyFeatures: ["RTL Synthesis", "Floorplanning", "Placement & Routing", "Static Timing Analysis"],
        details: "This project documents the complete backend digital design flow for an 8-bit subtractor circuit, implemented using Synopsys EDA tools.",
    },
];
